### ISSUE TITLE
YOU HAVE YOUR TOKEN IN HERE

### ISSUE THREAD

**Issue by Addoie** [Spimy/Discord.JS-Bot-Developement#2]
GITHUB IS NOT PRIVATE YOU NEED TO REMOVE YOUR TOKEN FROM HERE OR SOMEONE IS GOING TO SPAM YOU USING IT

**Comment by Spimy** [comment]
> GITHUB IS NOT PRIVATE YOU NEED TO REMOVE YOUR TOKEN FROM HERE OR SOMEONE IS GOING TO SPAM YOU USING IT

I've reset my bot token, dw
